site_name: 络绎直播
nav:
  - 首页: 
    - Main: 'index.md'
    - 话题: './luoyi/topic.md'
    - 搜索: './luoyi/search.md'
  - 用户: 
    - Main: './user/user.md'
    - Profile: './luoyi/profile.md'
    - 个人主页: './luoyi/user.md'
    - 关注/好友: './luoyi/fans.md'
  - 直播: 
    - Main: './luoyi/meeting.md'
  - 科学家: 
    - Main: './luoyi/scientist.md'
  - 论文: 
    - Main: './luoyi/article.md'
  - 通知: 
    - Main: './luoyi/im.md'

  - 管理后台: 
    - Main: './admin/admin.md'  
    - 系统管理: './admin/admin_sys.md'  
    - 用户管理: './admin/admin_user.md'  
    - 标签管理: './admin/admin_tag.md'  
    - 论文管理: './admin/admin_article.md'  
    - 会议管理: './admin/admin_meeting.md'  
    - 用户配置管理: './admin/admin_profile.md'  
    - 专辑管理: './admin/admin_album.md'  
    - 推荐管理: './admin/admin_banner.md'  
  
